/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class clockJNI {
  public final static native long bt_ctf_clock_create(String jarg1);
  public final static native int bt_ctf_clock_set_description(long jarg1, String jarg2);
  public final static native int bt_ctf_clock_set_frequency(long jarg1, long jarg2);
  public final static native int bt_ctf_clock_set_precision(long jarg1, long jarg2);
  public final static native int bt_ctf_clock_set_offset_s(long jarg1, long jarg2);
  public final static native int bt_ctf_clock_set_offset(long jarg1, long jarg2);
  public final static native int bt_ctf_clock_set_is_absolute(long jarg1, int jarg2);
  public final static native int bt_ctf_clock_set_time(long jarg1, long jarg2);
  public final static native void bt_ctf_clock_get(long jarg1);
  public final static native void bt_ctf_clock_put(long jarg1);
}
