/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class clock {
  public static SWIGTYPE_p_bt_ctf_clock bt_ctf_clock_create(String name) {
    long cPtr = clockJNI.bt_ctf_clock_create(name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_clock(cPtr, false);
  }

  public static int bt_ctf_clock_set_description(SWIGTYPE_p_bt_ctf_clock clock, String desc) {
    return clockJNI.bt_ctf_clock_set_description(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock), desc);
  }

  public static int bt_ctf_clock_set_frequency(SWIGTYPE_p_bt_ctf_clock clock, SWIGTYPE_p_uint64_t freq) {
    return clockJNI.bt_ctf_clock_set_frequency(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock), SWIGTYPE_p_uint64_t.getCPtr(freq));
  }

  public static int bt_ctf_clock_set_precision(SWIGTYPE_p_bt_ctf_clock clock, SWIGTYPE_p_uint64_t precision) {
    return clockJNI.bt_ctf_clock_set_precision(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock), SWIGTYPE_p_uint64_t.getCPtr(precision));
  }

  public static int bt_ctf_clock_set_offset_s(SWIGTYPE_p_bt_ctf_clock clock, SWIGTYPE_p_uint64_t offset_s) {
    return clockJNI.bt_ctf_clock_set_offset_s(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock), SWIGTYPE_p_uint64_t.getCPtr(offset_s));
  }

  public static int bt_ctf_clock_set_offset(SWIGTYPE_p_bt_ctf_clock clock, SWIGTYPE_p_uint64_t offset) {
    return clockJNI.bt_ctf_clock_set_offset(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock), SWIGTYPE_p_uint64_t.getCPtr(offset));
  }

  public static int bt_ctf_clock_set_is_absolute(SWIGTYPE_p_bt_ctf_clock clock, int is_absolute) {
    return clockJNI.bt_ctf_clock_set_is_absolute(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock), is_absolute);
  }

  public static int bt_ctf_clock_set_time(SWIGTYPE_p_bt_ctf_clock clock, SWIGTYPE_p_uint64_t time) {
    return clockJNI.bt_ctf_clock_set_time(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock), SWIGTYPE_p_uint64_t.getCPtr(time));
  }

  public static void bt_ctf_clock_get(SWIGTYPE_p_bt_ctf_clock clock) {
    clockJNI.bt_ctf_clock_get(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock));
  }

  public static void bt_ctf_clock_put(SWIGTYPE_p_bt_ctf_clock clock) {
    clockJNI.bt_ctf_clock_put(SWIGTYPE_p_bt_ctf_clock.getCPtr(clock));
  }

}
