/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class event_types {
  public static SWIGTYPE_p_bt_ctf_field_type bt_ctf_field_type_integer_create(long size) {
    long cPtr = event_typesJNI.bt_ctf_field_type_integer_create(size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_field_type(cPtr, false);
  }

  public static int bt_ctf_field_type_integer_set_signed(SWIGTYPE_p_bt_ctf_field_type integer, int is_signed) {
    return event_typesJNI.bt_ctf_field_type_integer_set_signed(SWIGTYPE_p_bt_ctf_field_type.getCPtr(integer), is_signed);
  }

  public static int bt_ctf_field_type_integer_set_base(SWIGTYPE_p_bt_ctf_field_type integer, bt_ctf_integer_base base) {
    return event_typesJNI.bt_ctf_field_type_integer_set_base(SWIGTYPE_p_bt_ctf_field_type.getCPtr(integer), base.swigValue());
  }

  public static int bt_ctf_field_type_integer_set_encoding(SWIGTYPE_p_bt_ctf_field_type integer, SWIGTYPE_ctf_string_encoding encoding) {
    return event_typesJNI.bt_ctf_field_type_integer_set_encoding(SWIGTYPE_p_bt_ctf_field_type.getCPtr(integer), encoding.swigValue());
  }

  public static SWIGTYPE_p_bt_ctf_field_type bt_ctf_field_type_enumeration_create(SWIGTYPE_p_bt_ctf_field_type integer_container_type) {
    long cPtr = event_typesJNI.bt_ctf_field_type_enumeration_create(SWIGTYPE_p_bt_ctf_field_type.getCPtr(integer_container_type));
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_field_type(cPtr, false);
  }

  public static int bt_ctf_field_type_enumeration_add_mapping(SWIGTYPE_p_bt_ctf_field_type enumeration, String string, SWIGTYPE_p_int64_t range_start, SWIGTYPE_p_int64_t range_end) {
    return event_typesJNI.bt_ctf_field_type_enumeration_add_mapping(SWIGTYPE_p_bt_ctf_field_type.getCPtr(enumeration), string, SWIGTYPE_p_int64_t.getCPtr(range_start), SWIGTYPE_p_int64_t.getCPtr(range_end));
  }

  public static SWIGTYPE_p_bt_ctf_field_type bt_ctf_field_type_floating_point_create() {
    long cPtr = event_typesJNI.bt_ctf_field_type_floating_point_create();
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_field_type(cPtr, false);
  }

  public static int bt_ctf_field_type_floating_point_set_exponent_digits(SWIGTYPE_p_bt_ctf_field_type floating_point, long exponent_digits) {
    return event_typesJNI.bt_ctf_field_type_floating_point_set_exponent_digits(SWIGTYPE_p_bt_ctf_field_type.getCPtr(floating_point), exponent_digits);
  }

  public static int bt_ctf_field_type_floating_point_set_mantissa_digits(SWIGTYPE_p_bt_ctf_field_type floating_point, long mantissa_digits) {
    return event_typesJNI.bt_ctf_field_type_floating_point_set_mantissa_digits(SWIGTYPE_p_bt_ctf_field_type.getCPtr(floating_point), mantissa_digits);
  }

  public static SWIGTYPE_p_bt_ctf_field_type bt_ctf_field_type_structure_create() {
    long cPtr = event_typesJNI.bt_ctf_field_type_structure_create();
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_field_type(cPtr, false);
  }

  public static int bt_ctf_field_type_structure_add_field(SWIGTYPE_p_bt_ctf_field_type structure, SWIGTYPE_p_bt_ctf_field_type field_type, String field_name) {
    return event_typesJNI.bt_ctf_field_type_structure_add_field(SWIGTYPE_p_bt_ctf_field_type.getCPtr(structure), SWIGTYPE_p_bt_ctf_field_type.getCPtr(field_type), field_name);
  }

  public static SWIGTYPE_p_bt_ctf_field_type bt_ctf_field_type_variant_create(SWIGTYPE_p_bt_ctf_field_type enum_tag, String tag_name) {
    long cPtr = event_typesJNI.bt_ctf_field_type_variant_create(SWIGTYPE_p_bt_ctf_field_type.getCPtr(enum_tag), tag_name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_field_type(cPtr, false);
  }

  public static int bt_ctf_field_type_variant_add_field(SWIGTYPE_p_bt_ctf_field_type variant, SWIGTYPE_p_bt_ctf_field_type field_type, String field_name) {
    return event_typesJNI.bt_ctf_field_type_variant_add_field(SWIGTYPE_p_bt_ctf_field_type.getCPtr(variant), SWIGTYPE_p_bt_ctf_field_type.getCPtr(field_type), field_name);
  }

  public static SWIGTYPE_p_bt_ctf_field_type bt_ctf_field_type_array_create(SWIGTYPE_p_bt_ctf_field_type element_type, long length) {
    long cPtr = event_typesJNI.bt_ctf_field_type_array_create(SWIGTYPE_p_bt_ctf_field_type.getCPtr(element_type), length);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_field_type(cPtr, false);
  }

  public static SWIGTYPE_p_bt_ctf_field_type bt_ctf_field_type_sequence_create(SWIGTYPE_p_bt_ctf_field_type element_type, String length_field_name) {
    long cPtr = event_typesJNI.bt_ctf_field_type_sequence_create(SWIGTYPE_p_bt_ctf_field_type.getCPtr(element_type), length_field_name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_field_type(cPtr, false);
  }

  public static SWIGTYPE_p_bt_ctf_field_type bt_ctf_field_type_string_create() {
    long cPtr = event_typesJNI.bt_ctf_field_type_string_create();
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_field_type(cPtr, false);
  }

  public static int bt_ctf_field_type_string_set_encoding(SWIGTYPE_p_bt_ctf_field_type string, SWIGTYPE_ctf_string_encoding encoding) {
    return event_typesJNI.bt_ctf_field_type_string_set_encoding(SWIGTYPE_p_bt_ctf_field_type.getCPtr(string), encoding.swigValue());
  }

  public static int bt_ctf_field_type_set_alignment(SWIGTYPE_p_bt_ctf_field_type type, long alignment) {
    return event_typesJNI.bt_ctf_field_type_set_alignment(SWIGTYPE_p_bt_ctf_field_type.getCPtr(type), alignment);
  }

  public static int bt_ctf_field_type_set_byte_order(SWIGTYPE_p_bt_ctf_field_type type, SWIGTYPE_bt_ctf_byte_order byte_order) {
    return event_typesJNI.bt_ctf_field_type_set_byte_order(SWIGTYPE_p_bt_ctf_field_type.getCPtr(type), byte_order.swigValue());
  }

  public static void bt_ctf_field_type_get(SWIGTYPE_p_bt_ctf_field_type type) {
    event_typesJNI.bt_ctf_field_type_get(SWIGTYPE_p_bt_ctf_field_type.getCPtr(type));
  }

  public static void bt_ctf_field_type_put(SWIGTYPE_p_bt_ctf_field_type type) {
    event_typesJNI.bt_ctf_field_type_put(SWIGTYPE_p_bt_ctf_field_type.getCPtr(type));
  }

}
