/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class event_typesJNI {
  public final static native int BT_CTF_INTEGER_BASE_UNKNOWN_get();
  public final static native int BT_CTF_INTEGER_BASE_BINARY_get();
  public final static native int BT_CTF_INTEGER_BASE_OCTAL_get();
  public final static native int BT_CTF_INTEGER_BASE_DECIMAL_get();
  public final static native int BT_CTF_INTEGER_BASE_HEXADECIMAL_get();
  public final static native long bt_ctf_field_type_integer_create(long jarg1);
  public final static native int bt_ctf_field_type_integer_set_signed(long jarg1, int jarg2);
  public final static native int bt_ctf_field_type_integer_set_base(long jarg1, int jarg2);
  public final static native int bt_ctf_field_type_integer_set_encoding(long jarg1, int jarg2);
  public final static native long bt_ctf_field_type_enumeration_create(long jarg1);
  public final static native int bt_ctf_field_type_enumeration_add_mapping(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native long bt_ctf_field_type_floating_point_create();
  public final static native int bt_ctf_field_type_floating_point_set_exponent_digits(long jarg1, long jarg2);
  public final static native int bt_ctf_field_type_floating_point_set_mantissa_digits(long jarg1, long jarg2);
  public final static native long bt_ctf_field_type_structure_create();
  public final static native int bt_ctf_field_type_structure_add_field(long jarg1, long jarg2, String jarg3);
  public final static native long bt_ctf_field_type_variant_create(long jarg1, String jarg2);
  public final static native int bt_ctf_field_type_variant_add_field(long jarg1, long jarg2, String jarg3);
  public final static native long bt_ctf_field_type_array_create(long jarg1, long jarg2);
  public final static native long bt_ctf_field_type_sequence_create(long jarg1, String jarg2);
  public final static native long bt_ctf_field_type_string_create();
  public final static native int bt_ctf_field_type_string_set_encoding(long jarg1, int jarg2);
  public final static native int bt_ctf_field_type_set_alignment(long jarg1, long jarg2);
  public final static native int bt_ctf_field_type_set_byte_order(long jarg1, int jarg2);
  public final static native void bt_ctf_field_type_get(long jarg1);
  public final static native void bt_ctf_field_type_put(long jarg1);
}
