/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class eventJNI {
  public final static native long bt_ctf_event_class_create(String jarg1);
  public final static native int bt_ctf_event_class_add_field(long jarg1, long jarg2, String jarg3);
  public final static native void bt_ctf_event_class_get(long jarg1);
  public final static native void bt_ctf_event_class_put(long jarg1);
  public final static native long bt_ctf_event_create(long jarg1);
  public final static native int bt_ctf_event_set_payload(long jarg1, String jarg2, long jarg3);
  public final static native long bt_ctf_event_get_payload(long jarg1, String jarg2);
  public final static native void bt_ctf_event_get(long jarg1);
  public final static native void bt_ctf_event_put(long jarg1);
}
