/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class event_fieldsJNI {
  public final static native long bt_ctf_field_create(long jarg1);
  public final static native long bt_ctf_field_structure_get_field(long jarg1, String jarg2);
  public final static native long bt_ctf_field_array_get_field(long jarg1, long jarg2);
  public final static native int bt_ctf_field_sequence_set_length(long jarg1, long jarg2);
  public final static native long bt_ctf_field_sequence_get_field(long jarg1, long jarg2);
  public final static native long bt_ctf_field_variant_get_field(long jarg1, long jarg2);
  public final static native long bt_ctf_field_enumeration_get_container(long jarg1);
  public final static native int bt_ctf_field_signed_integer_set_value(long jarg1, long jarg2);
  public final static native int bt_ctf_field_unsigned_integer_set_value(long jarg1, long jarg2);
  public final static native int bt_ctf_field_floating_point_set_value(long jarg1, double jarg2);
  public final static native int bt_ctf_field_string_set_value(long jarg1, String jarg2);
  public final static native void bt_ctf_field_get(long jarg1);
  public final static native void bt_ctf_field_put(long jarg1);
}
