/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class streamJNI {
  public final static native long bt_ctf_stream_class_create(String jarg1);
  public final static native int bt_ctf_stream_class_set_clock(long jarg1, long jarg2);
  public final static native int bt_ctf_stream_class_add_event_class(long jarg1, long jarg2);
  public final static native void bt_ctf_stream_class_get(long jarg1);
  public final static native void bt_ctf_stream_class_put(long jarg1);
  public final static native void bt_ctf_stream_append_discarded_events(long jarg1, long jarg2);
  public final static native int bt_ctf_stream_append_event(long jarg1, long jarg2);
  public final static native int bt_ctf_stream_flush(long jarg1);
  public final static native void bt_ctf_stream_get(long jarg1);
  public final static native void bt_ctf_stream_put(long jarg1);
}
