/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class stream {
  public static SWIGTYPE_p_bt_ctf_stream_class bt_ctf_stream_class_create(String name) {
    long cPtr = streamJNI.bt_ctf_stream_class_create(name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bt_ctf_stream_class(cPtr, false);
  }

  public static int bt_ctf_stream_class_set_clock(SWIGTYPE_p_bt_ctf_stream_class stream_class, SWIGTYPE_p_bt_ctf_clock clock) {
    return streamJNI.bt_ctf_stream_class_set_clock(SWIGTYPE_p_bt_ctf_stream_class.getCPtr(stream_class), SWIGTYPE_p_bt_ctf_clock.getCPtr(clock));
  }

  public static int bt_ctf_stream_class_add_event_class(SWIGTYPE_p_bt_ctf_stream_class stream_class, SWIGTYPE_p_bt_ctf_event_class event_class) {
    return streamJNI.bt_ctf_stream_class_add_event_class(SWIGTYPE_p_bt_ctf_stream_class.getCPtr(stream_class), SWIGTYPE_p_bt_ctf_event_class.getCPtr(event_class));
  }

  public static void bt_ctf_stream_class_get(SWIGTYPE_p_bt_ctf_stream_class stream_class) {
    streamJNI.bt_ctf_stream_class_get(SWIGTYPE_p_bt_ctf_stream_class.getCPtr(stream_class));
  }

  public static void bt_ctf_stream_class_put(SWIGTYPE_p_bt_ctf_stream_class stream_class) {
    streamJNI.bt_ctf_stream_class_put(SWIGTYPE_p_bt_ctf_stream_class.getCPtr(stream_class));
  }

  public static void bt_ctf_stream_append_discarded_events(SWIGTYPE_p_bt_ctf_stream stream, SWIGTYPE_p_uint64_t event_count) {
    streamJNI.bt_ctf_stream_append_discarded_events(SWIGTYPE_p_bt_ctf_stream.getCPtr(stream), SWIGTYPE_p_uint64_t.getCPtr(event_count));
  }

  public static int bt_ctf_stream_append_event(SWIGTYPE_p_bt_ctf_stream stream, SWIGTYPE_p_bt_ctf_event event) {
    return streamJNI.bt_ctf_stream_append_event(SWIGTYPE_p_bt_ctf_stream.getCPtr(stream), SWIGTYPE_p_bt_ctf_event.getCPtr(event));
  }

  public static int bt_ctf_stream_flush(SWIGTYPE_p_bt_ctf_stream stream) {
    return streamJNI.bt_ctf_stream_flush(SWIGTYPE_p_bt_ctf_stream.getCPtr(stream));
  }

  public static void bt_ctf_stream_get(SWIGTYPE_p_bt_ctf_stream stream) {
    streamJNI.bt_ctf_stream_get(SWIGTYPE_p_bt_ctf_stream.getCPtr(stream));
  }

  public static void bt_ctf_stream_put(SWIGTYPE_p_bt_ctf_stream stream) {
    streamJNI.bt_ctf_stream_put(SWIGTYPE_p_bt_ctf_stream.getCPtr(stream));
  }

}
