/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "babeltrace/ctf-writer/event-types.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_event_1typesJNI_BT_1CTF_1INTEGER_1BASE_1UNKNOWN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum bt_ctf_integer_base result;
  
  (void)jenv;
  (void)jcls;
  result = (enum bt_ctf_integer_base)BT_CTF_INTEGER_BASE_UNKNOWN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_BT_1CTF_1INTEGER_1BASE_1BINARY_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum bt_ctf_integer_base result;
  
  (void)jenv;
  (void)jcls;
  result = (enum bt_ctf_integer_base)BT_CTF_INTEGER_BASE_BINARY;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_BT_1CTF_1INTEGER_1BASE_1OCTAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum bt_ctf_integer_base result;
  
  (void)jenv;
  (void)jcls;
  result = (enum bt_ctf_integer_base)BT_CTF_INTEGER_BASE_OCTAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_BT_1CTF_1INTEGER_1BASE_1DECIMAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum bt_ctf_integer_base result;
  
  (void)jenv;
  (void)jcls;
  result = (enum bt_ctf_integer_base)BT_CTF_INTEGER_BASE_DECIMAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_BT_1CTF_1INTEGER_1BASE_1HEXADECIMAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum bt_ctf_integer_base result;
  
  (void)jenv;
  (void)jcls;
  result = (enum bt_ctf_integer_base)BT_CTF_INTEGER_BASE_HEXADECIMAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1integer_1create(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  struct bt_ctf_field_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  result = (struct bt_ctf_field_type *)bt_ctf_field_type_integer_create(arg1);
  *(struct bt_ctf_field_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1integer_1set_1signed(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)bt_ctf_field_type_integer_set_signed(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1integer_1set_1base(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  enum bt_ctf_integer_base arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (enum bt_ctf_integer_base)jarg2; 
  result = (int)bt_ctf_field_type_integer_set_base(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1integer_1set_1encoding(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  enum ctf_string_encoding arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (enum ctf_string_encoding)jarg2; 
  result = (int)bt_ctf_field_type_integer_set_encoding(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1enumeration_1create(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  struct bt_ctf_field_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  result = (struct bt_ctf_field_type *)bt_ctf_field_type_enumeration_create(arg1);
  *(struct bt_ctf_field_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1enumeration_1add_1mapping(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  char *arg2 = (char *) 0 ;
  int64_t arg3 ;
  int64_t arg4 ;
  int64_t *argp3 ;
  int64_t *argp4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  argp3 = *(int64_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int64_t");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(int64_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null int64_t");
    return 0;
  }
  arg4 = *argp4; 
  result = (int)bt_ctf_field_type_enumeration_add_mapping(arg1,(char const *)arg2,arg3,arg4);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1floating_1point_1create(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct bt_ctf_field_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct bt_ctf_field_type *)bt_ctf_field_type_floating_point_create();
  *(struct bt_ctf_field_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1floating_1point_1set_1exponent_1digits(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)bt_ctf_field_type_floating_point_set_exponent_digits(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1floating_1point_1set_1mantissa_1digits(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)bt_ctf_field_type_floating_point_set_mantissa_digits(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1structure_1create(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct bt_ctf_field_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct bt_ctf_field_type *)bt_ctf_field_type_structure_create();
  *(struct bt_ctf_field_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1structure_1add_1field(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  struct bt_ctf_field_type *arg2 = (struct bt_ctf_field_type *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = *(struct bt_ctf_field_type **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)bt_ctf_field_type_structure_add_field(arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1variant_1create(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  char *arg2 = (char *) 0 ;
  struct bt_ctf_field_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (struct bt_ctf_field_type *)bt_ctf_field_type_variant_create(arg1,(char const *)arg2);
  *(struct bt_ctf_field_type **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1variant_1add_1field(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jstring jarg3) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  struct bt_ctf_field_type *arg2 = (struct bt_ctf_field_type *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = *(struct bt_ctf_field_type **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  result = (int)bt_ctf_field_type_variant_add_field(arg1,arg2,(char const *)arg3);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1array_1create(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  unsigned int arg2 ;
  struct bt_ctf_field_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (struct bt_ctf_field_type *)bt_ctf_field_type_array_create(arg1,arg2);
  *(struct bt_ctf_field_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1sequence_1create(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jlong jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  char *arg2 = (char *) 0 ;
  struct bt_ctf_field_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (struct bt_ctf_field_type *)bt_ctf_field_type_sequence_create(arg1,(char const *)arg2);
  *(struct bt_ctf_field_type **)&jresult = result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1string_1create(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct bt_ctf_field_type *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct bt_ctf_field_type *)bt_ctf_field_type_string_create();
  *(struct bt_ctf_field_type **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1string_1set_1encoding(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  enum ctf_string_encoding arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (enum ctf_string_encoding)jarg2; 
  result = (int)bt_ctf_field_type_string_set_encoding(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1set_1alignment(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)bt_ctf_field_type_set_alignment(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1set_1byte_1order(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  enum bt_ctf_byte_order arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  arg2 = (enum bt_ctf_byte_order)jarg2; 
  result = (int)bt_ctf_field_type_set_byte_order(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  bt_ctf_field_type_get(arg1);
}


SWIGEXPORT void JNICALL Java_event_1typesJNI_bt_1ctf_1field_1type_1put(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct bt_ctf_field_type *arg1 = (struct bt_ctf_field_type *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct bt_ctf_field_type **)&jarg1; 
  bt_ctf_field_type_put(arg1);
}


#ifdef __cplusplus
}
#endif

